added Product table migration
circuitfox/csc3700-fireworks pull request #1
Opened 2017-04-09 00:04 UTC by carlgoshert

I ran "php artisan migrate" on my machine to make sure it works

2017-04-09 00:05 UTC, carlgoshert commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add Product table](https://trello.com/c/MwcEQZ9e/24-add-product-table)

2017-04-09 00:10 UTC, circuitfox commented
Alright. This looks good. I'd like a test to make sure the migration runs correctly though.

2017-04-09 00:39 UTC, circuitfox commented
Also, the column names should be in `snake_case` not `camelCase`, that seems to be the convention that Laravel uses.

2017-04-09 01:24 UTC, circuitfox requested changes

2017-04-09 01:24 UTC, circuitfox commented on database/migrations/2017_04_07_231938_create_product_table.php
> +        Schema::create('Product', function (Blueprint $table) {
The columns in camelCase here should be rewritten as snake_case. `catalogPage` becomes `catalog_page`, etc.

2017-04-09 23:17 UTC, carlgoshert commented
updated based on requested changes

2017-04-10 01:17 UTC, circuitfox requested changes

2017-04-10 01:17 UTC, circuitfox commented on database/migrations/2017_04_07_231938_create_product_table.php
> +        Schema::dropIfExists('Product');
This should be 'product'.

2017-04-10 01:26 UTC, circuitfox approved these changes

2017-04-10 01:27 UTC, merged